apiVersion: v1
kind: Namespace
metadata:
  name: ketiops-kafka
---
# kafka6 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka6
  namespace: ketiops-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka6
  template:
    metadata:
      labels:
        app: kafka6
    spec:
      nodeSelector:
        kubernetes.io/hostname: ketiops-gpu-node-6
      containers:
      - name: kafka6
        image: confluentinc/cp-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: 'CONTROLLER'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        - name: KAFKA_LISTENERS
          value: 'INTERNAL://localhost:29092,CONTROLLER://localhost:29093,EXTERNAL://0.0.0.0:9092'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'INTERNAL://localhost:29092,EXTERNAL://10.0.1.115:31006'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'INTERNAL'
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: '1@localhost:29093'
        - name: KAFKA_PROCESS_ROLES
          value: 'broker,controller'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "3"
        - name: CLUSTER_ID
          value: 'ciWo7IWazngRchmPES6q5A=='
        - name: KAFKA_LOG_DIRS
          value: '/tmp/kraft-combined-logs'
---
# kafka6 Service
apiVersion: v1
kind: Service
metadata:
  name: kafka6-service
  namespace: ketiops-kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 31006
  selector:
    app: kafka6

