apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ketiops-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ketiops-kafka
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 32000
  selector:
    app: mysql