apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-cpu-limit
  namespace: microservice
  labels:
    app: stress
spec:
  selector:
    matchLabels:
      stress-area: here
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stress-area: here
    spec:
      containers:
      - name: microservice-cpu-limit
        image: mohsenmottaghi/container-stress:latest
        command: ["stress", "--verbose", "--vm", "1", "--vm-bytes", "10"]
         # If you don`t know why you should define these elements, Don`t change them !
         # Check commands in README.md
        resources:
          limits:
            memory: "1200Mi"
            cpu: "5000m"
          requests:
            memory: "1000Mi"
            cpu: "10m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-cpu
  namespace: microservice
spec:
  maxReplicas: 3 # 최대 레플리카 수
  minReplicas: 1 # 최소 레플리카 수
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice-cpu-limit
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # 평균 CPU 사용량이 70% 이상인 경우 Scale Out 이하인 경우 Scale In
