apiVersion: v1
kind: Service
metadata:
  name: microservice-mem-svc
  namespace: hpa
spec:
  selector:
    app: microservice-mem-svc
  type: NodePort
  ports:
    - nodePort: 30332
      port: 5000
      targetPort: 5000
