apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-mem-hpa
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice-mem
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 10
          periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
