# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: microservice-rps
 namespace: hpa
spec:
 selector:
   matchLabels:
      resource: rps
 replicas: 1 
 template:
   metadata:
     labels:
       resource: rps
   spec:
     nodeName: ketiops-gpu-node-1
     containers:
     - name: container
       image: kubetm/app:v1
