apiVersion: v1
kind: Service
metadata:
 name: microservice-rps-svc
 namespace: hpa
spec:
 selector:
    resource: rps
 ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30331
 type: NodePort
